exports.messages = 
{
    TRUE : 1,
    FALSE : 0,
    JWT_STRING : "nodejsmobylapi",
    REQUIRED : "this field is required..!",
    PASS_REQUIRED : "password required..!",
    EMAIL_REQUIRED : "email required..!",
    NUMBER : "this field is allow only numbers..!",
    BOOLEAN : "this field is allow only 0 or 1..!",
    STRING : "this field is allow string..!",
    OTP : "otp should contain 6 digits..!",
    OTP_IS_REQUIRED : "otp is required for this order..!",
    USER_ALREADY_REGISTERED : "this user is already registered..!",
    ALREADY_REGISTERED : "this mobile number is already registered..!",
    EMAIL_NOT_EXISTS : "email id is not exists in this profile..!",
    INVALID_GENDER : "invalid gender..!",
    SOMETHING_WENT_WRONG : "something went's wrong..!",
    LOGIN_SUCCESS : "login successfully..!",
    USER_REGISTER : "user register successfully..!",
    USER_NOT_EXISTS : "user not exists..!",
    USER_EMAIL_NOT_EXISTS : "Invalid username and password",
    PASSWORD_NOT_MATCH : "Existing password is not matched..!",
    BLOCKED_USER : "user has been blocked..!",
    CHANGE_PASSWORD_SUCCESSFULLY : "change password successfully..!",
    DATA_ADD_SUCCESSFULLY : "data added successfully..!",
    DATA_UPDATE_SUCCESSFULLY : "data updated successfully..!",
    DATA_DELETE_SUCCESSFULLY : "data deleted successfully..!",
    DATA_SHARE_SUCCESSFULLY : "data shared successfully..!",
    DATA_GET_SUCCESSFULLY : "data get successfully..!",
    ALREADY_REGISTERED_EMAIL : "this email is already registered..!",
    USER_LOGIN : "login successfully..!",
    CATEGORY_NAME_EXISTS : "this category name is already exists. Please insert a unique name..!",
    CATEGORY_NOT_EXISTS : "this category is not exists..!",
    CATEGORY_ENABLE : "this category status is enabled..!",
    CATEGORY_NOT_QUESTION_EXISTS : "this category has no question..!",
    PARENT_CATEGORY_REQUIRED : "parent category field is required..!",
    INQUIRY_NOT_EXISTS : "inquiry not exists..!",
    ANSWER_NOT_EXISTS : "this answer is not exists..!",
    QUESTION_NOT_EXISTS : "this question is not exists..!",
    ONE_QUESTION_EXISTS : "question already added. please enter sub quetion..!",
    QUESTION_OR_CATEGORY_NOT_EXISTS : "this question or category is not exists..!",
    CONTACT_DETAILS_REGISTERED : "this email or contact no is registered with new user..!",
    SOMETHING_NOT_EXISTS : "this category or question or option is not exists..!",
    PRICE_ALREADY_EXISTS : "this price is already exists..!",
    PRICE_NOT_EXISTS : "this price is not exists..!",
    PACKAGE_NAME_EXISTS : "this package title is already exists. Please insert a unique title..!",
    PACKAGE_NOT_EXISTS : "this package is not exists..!",
    ADDRESS_NOT_EXISTS : "this address is not exists..!",
    OTP_NOT_EXISTS : "this otp is not exists..!",
    ALREADY_CREATED_COUPON : "this coupon name is already exists. Please insert a unique name..!",
    COUPON_CODE_NOT_EXISTS: "this coupon code is not exists..!",
    COUPON_CODE_NOT_MATCH: "Coupone dosen't match with our system..!",
    COUPON_CODE_ALREADY_USED: "this coupon code is used..!",
    COUPON_CODE_APPLIED: "coupon code applied successfully..!",
    COUPON_CODE_EXPIRED: "coupon code has been expired..!",
    COUPON_CODE_MIN_ORDER_VALUE: "minimum order value not applicable..!",
    SUBSCRIPTION_ADDED: "thank you for subscribed print on demand..!",
    FILE_UPLOAD_SUCCESSFULL: "file upload successfully..!",
    DELIVERY_CHARGE_NOT_EXISTS: "this delivery charge is not exists..!",
    MENU_NOT_EXISTS : "this menu is not exists..!",
    PAGE_INSERT : "please add page first..!",
    MENU_ALREADY_EXISTS : "this menu is already exists..!",
    PAGE_NOT_EXISTS: "this page is not exists..!",
    HOW_WE_WORK_NOT_EXISTS: "this work is not exists..!",
    ORDER_NOT_FOUND: "this order is not exists..!",
    ORDER_STATUS: "order status updated successfully..!",
    TIMRLINE_NOT_EXISTS: "this timeline is not exists..!",
    ALLOCATE_ORDER_NOT_EXISTS: "this order is not exists..!",
    CURRENCY:"AED"
}
